---
title: "Sobremesas"
---

## Pudim de Leite

### Ingredientes {.unnumbered}
- 1 lata de leite condensado (395 g)
- 2 medidas (da lata) de Leite
- 3 ovos

### Modo de preparo {.unnumbered}
1. Derreta o açúcar até ficar dourado dentro da própria forma.
2. Em um liquidificador, acrescente o leite condensado, o leite e os ovos. Bata até obter uma consistência homogênea e despeje na forma.
3. Cubra com papel-alumínio e leve ao forno médio (180°C), em banho-maria, por cerca de 2 horas.
4. Depois de frio, leve o pudim de leite condensado para gelar por cerca de 6 horas.

## Tiramisu

### Ingredientes {.unnumbered}
- 1½ xícara (chá) de mascarpone (cerca de 350 g)
- 4 ovos
- ½ xícara (chá) de açúcar
- ¾ de xícara (chá) de café forte coado sem açúcar
- ¼ de xícara (chá) de conhaque (ou o licor de sua preferência)
- biscoitos champanhe caseiros
- cacau em pó a gosto para polvilhar

### Modo de preparo {.unnumbered}
1. Numa tigela pequena, quebre um ovo de cada vez, separando a clara da gema. Transfira as claras para uma tigela e as gemas para a tigela da batedeira. Leve uma panela com um pouco de água ao fogo baixo para ferver – ela vai ser usada para aquecer as claras em banho-maria.
2. Acrescente ¼ de xícara (chá) do açúcar às gemas e bata até formar um creme claro – no meio do processo, pare de bater e raspe a lateral da tigela com uma espátula para bater de maneira uniforme. Junte o mascarpone e bata apenas para incorporar. Transfira o creme para outra tigela e reserve. Lave e seque bem a tigela e o globo da batedeira.
3. Junte o restante do açúcar às claras e encaixe a tigela na panela do banho-maria. Mexa com uma espátula até aquecer e o açúcar dissolver – cuidado para não cozinhar a clara. Com a espátula levante uma porção da mistura e, com a ponta dos dedos, verifique se as claras estão aquecidas sem grãozinhos de açúcar.
4. Transfira a mistura de claras e açúcar para a batedeira e bata até formar um merengue bem leve – cuidado para não bater em excesso, pois fica mais difícil incorporar o creme de mascarpone a um merengue muito firme. Bata até o merengue formar picos. Adicione ⅓ do merengue ao creme de mascarpone e mexa bem com a espátula para incorporar. Junte o restante aos poucos, mexendo delicadamente, de baixo para cima. Reserve.
5. Separe uma travessa retangular de cerca de 30 cm x 20 cm. Num prato fundo, misture o café com o licor.
6. Molhe apenas um dos lados dos biscoitos no café com licor e transfira para a travessa, com o lado molhado virado para cima, um ao lado do outro até cobrir todo o fundo. Espalhe metade do creme sobre os biscoitos, cobrindo toda a superfície. Faça outra camada de biscoitos umedecidos e cubra com o restante do creme. Nivele com a espátula e leve à geladeira para firmar por pelo menos 6 horas (se preferir, monte a sobremesa, cubra com filme e deixe na geladeira de um dia para o outro).
7. Na hora de servir, retire o tiramisu da geladeira e polvilhe com cacau em pó, passando por uma peneira fina.
