
---
title: "Sushi"
---

## Arroz de Sushi

### Ingredientes {.unnumbered}
- 300g de Arroz
- 380ml de água
- 80 ml molho su (60ml de vinagre de arroz, 2 colheres de açucar, 1 colher de chá rasa de sal)

### Modo de preparo {.unnumbered}
1. Lavar o arroz: Coloque o arroz em uma tigela, adicione um pouco de água e massageie delicadamente os grãos para liberar o excesso de amido.
2. Enxaguar: Descarte a água e repita a lavagem de 3 a 4 vezes, até que a água fique mais clara.
3. Iniciar o cozimento: Coloque o arroz na panela com a quantidade de água adequada, tampe e leve ao fogo mais baixo possível.
Não retire a tampa durante todo o cozimento.
4. Primeira etapa do cozimento: Deixe cozinhar por 15 minutos, até começar a ferver.
5. Segunda etapa do cozimento: Coloque um peso sobre a tampa da panela e deixe cozinhar por mais 15 minutos.
6. Finalização: Retire a tampa para liberar o vapor e eliminar o excesso de água.
7. Descanso: Deixe o arroz descansar por 20 minutos antes de servir.
8. Molho: Coloque o arroz em uma tijela grande e despeje o molho su.

## Sunomono

### Ingredientes {.unnumbered}
- 1 pepino 
- 1 colher de chá de sal
- 2 colher de sopa de açúcar (bem cheia)
- 65 ml de vinagre de arroz

### Modo de preparo {.unnumbered
1. Corte o pepino em rodelas bem finas.
2. Coloque o pepino em uma tigela, adicione 1 colher de chá de sal e misture bem. Deixe descansar por 20 a 30 minutos para que o pepino solte a água em uma peneira.
3. Em outro recipiente, misture o açúcar e o vinagre de arroz até dissolver bem.
4. Aperte levemente o pepino para retirar o excesso de água e depois despeje o molho por cima.
